# =============================================================================
# 03_make_Fig1.R — scRNA-seq panels montage
#
# This script renders a montage of panels; the letters used inside the montage
# (pB..pH) are internal identifiers only. The published figures are assembled
# in Illustrator, where the panels are distributed as follows:
#
#   montage pB  UMAP, cell type annotations        -> manuscript Figure 1B
#   montage pC  keratinocyte subcluster UMAP       -> manuscript Figure 1C
#   montage pD  FeaturePlot KRT31                  -> manuscript Figure S1C
#   montage pE  FeaturePlot KRT35                  -> manuscript Figure S1D
#   montage pF  FeaturePlot KRT85                  -> manuscript Figure S1E
#   montage pG  volcano, KRT35/85 KC DEGs          -> manuscript Figure 1D
#   montage pH  RAB7A violin, KRT35/85 KC          -> manuscript Figure 1E
#
# Manuscript Figure 1A (schematic) and Figure 1F (immunofluorescence) are not
# generated by this code.
#
# Input:  data.hair.rename.rds, keratinocytes.rds,
#         krt35_85_DEGs.rds, krt35_85_keratinocytes.rds
# Output: <figures>/Fig1_combined_BtoH.pdf
# =============================================================================

source("config.R")

library(Seurat)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(ggrepel)
library(patchwork)
library(cowplot)

require_input(c(rds_rename, rds_kc, rds_krt35_DEG, rds_krt35_85),
              produced_by = "01_analysis_pipeline.R and 02_keratinocyte_analysis.R",
              env_hint = "HAIR_PROCESSED_DIR / HAIR_KC_DIR")

# =============================================================================
# Panel B — UMAP with cell type annotations           [manuscript Figure 1B]
# =============================================================================
cat(">>> Panel B: Cell type UMAP ...\n")
rename <- readRDS(rds_rename)
DefaultAssay(rename) <- "RNA"

rename$cell_type_annotation <- unname(pub_labels[as.character(Idents(rename))])

pB <- DimPlot(rename, reduction = "umap", group.by = "cell_type_annotation",
              cols = celltype_colors, pt.size = 0.15,
              label = TRUE, repel = TRUE, label.size = 2.5) +
  theme_pub() +
  theme(legend.position = "right", legend.key.size = unit(0.25, "cm"))
rm(rename); gc()

# =============================================================================
# Panels C-F — Keratinocyte subclusters + FeaturePlots
#   pC -> manuscript Figure 1C
#   pD, pE, pF (KRT31, KRT35, KRT85) -> manuscript Figure S1C, S1D, S1E
# =============================================================================
cat(">>> Panels C-F: Keratinocyte subclusters ...\n")
keratinocytes <- readRDS(rds_kc)

n_clusters <- length(unique(keratinocytes$seurat_clusters))
palette_expanded <- rep(pub_colors, length.out = n_clusters)

pC <- DimPlot(keratinocytes, reduction = "umap",
              label = TRUE, repel = TRUE, label.size = 2.5,
              cols = palette_expanded, pt.size = 0.2) +
  theme_pub() +
  theme(legend.position = "right", legend.key.size = unit(0.2, "cm"))

make_feature <- function(obj, gene) {
  FeaturePlot(obj, features = gene,
              min.cutoff = "q10", max.cutoff = "q90",
              cols = c("lightgrey", "#BE3428"), pt.size = 0.3) +
    ggtitle(gene) +
    theme_pub() +
    theme(plot.title = element_text(size = 11, face = "bold.italic",
                                    hjust = 0.5, family = "Arial"))
}

pD <- make_feature(keratinocytes, "KRT31")
pE <- make_feature(keratinocytes, "KRT35")
pF <- make_feature(keratinocytes, "KRT85")
rm(keratinocytes); gc()

# =============================================================================
# Panel G — Volcano plot                              [manuscript Figure 1D]
#
# Note: p_val_adj comes from Seurat::FindMarkers (Wilcoxon), which applies a
# Bonferroni correction across all genes in the object.
# =============================================================================
cat(">>> Panel G: Volcano plot ...\n")
krt35_85_DEGs <- readRDS(rds_krt35_DEG)
krt35_85_DEGs$gene <- rownames(krt35_85_DEGs)

volcano_data <- krt35_85_DEGs %>%
  mutate(
    neg_log_pval = -log10(p_val_adj),
    direction = case_when(
      avg_log2FC > 0.25 & p_val_adj < 0.05 ~ "Up in Black",
      avg_log2FC < -0.25 & p_val_adj < 0.05 ~ "Up in Gray",
      TRUE ~ "NS"
    ),
    is_rab7a = gene == "RAB7A"
  )

volcano_data$neg_log_pval[is.infinite(volcano_data$neg_log_pval)] <-
  max(volcano_data$neg_log_pval[!is.infinite(volcano_data$neg_log_pval)]) * 1.05

n_up_black <- sum(volcano_data$direction == "Up in Black")
n_up_gray  <- sum(volcano_data$direction == "Up in Gray")

top_black <- volcano_data %>% filter(direction == "Up in Black") %>%
  arrange(p_val_adj) %>% head(10)
top_gray  <- volcano_data %>% filter(direction == "Up in Gray") %>%
  arrange(p_val_adj) %>% head(10)
sig_genes <- bind_rows(top_black, top_gray) %>% filter(gene != "RAB7A")

volcano_colors <- c("Up in Black" = "#2166AC", "Up in Gray" = "#B2182B", "NS" = "grey80")

pG <- ggplot(volcano_data, aes(x = avg_log2FC, y = neg_log_pval)) +
  geom_point(data = volcano_data %>% filter(direction == "NS"),
             color = "grey80", size = 1.0, alpha = 0.4) +
  geom_point(data = volcano_data %>% filter(direction != "NS"),
             aes(color = direction), size = 1.2, alpha = 0.7) +
  geom_point(data = volcano_data %>% filter(is_rab7a),
             color = "black", size = 3.5, shape = 21, fill = "red", stroke = 0.6) +
  geom_text_repel(data = sig_genes,
                  aes(label = gene, color = direction),
                  size = 2.2, max.overlaps = 25, fontface = "italic",
                  segment.size = 0.3, segment.color = "grey40",
                  box.padding = 0.3, show.legend = FALSE, seed = 42) +
  geom_text_repel(data = volcano_data %>% filter(is_rab7a),
                  aes(label = gene), color = "red", size = 3.2,
                  fontface = "bold.italic", box.padding = 0.7,
                  segment.color = "red", segment.size = 0.5,
                  min.segment.length = 0, seed = 42) +
  scale_color_manual(values = volcano_colors,
                     breaks = c("Up in Black", "Up in Gray"),
                     labels = c(sprintf("Up in Black (n = %d)", n_up_black),
                                sprintf("Up in Gray (n = %d)", n_up_gray))) +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed",
             color = "grey50", linewidth = 0.4) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed",
             color = "grey50", linewidth = 0.4) +
  labs(x = expression(Log[2]~"Fold Change (Black vs Gray)"),
       y = expression(-Log[10]~"Adjusted P-value"),
       color = NULL) +
  theme_pub() +
  theme(legend.position.inside = c(0.98, 0.98),
        legend.position = "inside",
        legend.justification = c(1, 1),
        legend.background = element_rect(fill = alpha("white", 0.8), color = NA),
        legend.key.size = unit(0.3, "cm"))

# =============================================================================
# Panel H — RAB7A violin                              [manuscript Figure 1E]
# =============================================================================
cat(">>> Panel H: RAB7A violin ...\n")
krt35_85 <- readRDS(rds_krt35_85)
DefaultAssay(krt35_85) <- "RNA"

rab7a_data <- data.frame(
  RAB7A    = FetchData(krt35_85, vars = "RAB7A")[, 1],
  Protocol = krt35_85$protocol
)
rab7a_data$Protocol <- factor(rab7a_data$Protocol,
                              levels = c("Black", "Grey"),
                              labels = c("Black", "Gray"))

pH <- ggplot(rab7a_data, aes(x = Protocol, y = RAB7A, fill = Protocol)) +
  geom_violin(trim = FALSE, alpha = 0.7, linewidth = 0.4) +
  geom_boxplot(width = 0.15, outlier.shape = NA, alpha = 0.9, linewidth = 0.4) +
  scale_fill_manual(values = hair_colors) +
  stat_compare_means(method = "wilcox.test", label = "p.format",
                     label.x = 1.5, vjust = -0.5, size = 3.2, family = "Arial") +
  labs(x = NULL, y = "RAB7A expression",
       subtitle = "Hair cortex keratinocytes") +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.12))) +
  theme_pub() +
  theme(legend.position = "none",
        plot.subtitle = element_text(size = 8, hjust = 0.5, color = "grey30",
                                     family = "Arial"))
rm(krt35_85, rab7a_data); gc()

# =============================================================================
# Assemble combined figure
# =============================================================================
cat(">>> Assembling Figure 1 ...\n")

row1 <- plot_grid(pB, pC, ncol = 2, rel_widths = c(6.0, 5.0),
                  labels = c("B", "C"), label_size = 14, label_fontface = "bold",
                  label_fontfamily = "Arial")
row2 <- plot_grid(pD, pE, pF, ncol = 3,
                  labels = c("D", "E", "F"), label_size = 14, label_fontface = "bold",
                  label_fontfamily = "Arial")
row3 <- plot_grid(pG, NULL, pH, ncol = 3, rel_widths = c(6.5, 0.5, 3.5),
                  labels = c("G", "", "H"), label_size = 14, label_fontface = "bold",
                  label_fontfamily = "Arial")

combined <- plot_grid(row1, row2, row3, ncol = 1, rel_heights = c(4.5, 4.0, 5.5))

out_pdf <- file.path(fig_dir, "Fig1_combined_BtoH.pdf")
cairo_pdf(out_pdf, width = 8.27, height = 9.0)
print(combined)
dev.off()

cat(sprintf("  Saved: %s\n", out_pdf))
cat("\n=== Figure 1 complete ===\n")
